### ISSUE TITLE
Look into Zodiac

### ISSUE THREAD

**Issue by mojeanmac** [cse110-sp23-group13/cse110-sp23-group13#15]
- Designing framework
- APIs? -- daily horoscope
- Maybe start on the HTML for pages

**Comment by emjinn** [comment]
Implemented basic zodiac functionality! Right now, it prompts the user to enter their birth date and birth month, and it outputs their zodiac sign. Will look into implementing a daily horoscope feature dependent on the user's zodiac sign soon!
